#!/bin/sh

MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
CURRENT_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)

FIVE_PERCENT_MAX=$(($MAX_BRIGHTNESS / 100 *5))

if [ "$1" = "up" ]; then
	NEXT_BRIGHTNESS=$(($CURRENT_BRIGHTNESS+$FIVE_PERCENT_MAX))
	if [ $NEXT_BRIGHTNESS -le $MAX_BRIGHTNESS ]; then
		echo $NEXT_BRIGHTNESS >> /sys/class/backlight/intel_backlight/brightness
	fi
elif [ "$1" = "down" ]; then
	NEXT_BRIGHTNESS=$(($CURRENT_BRIGHTNESS-$FIVE_PERCENT_MAX))
	if [ $NEXT_BRIGHTNESS -ge 0 ]; then
		echo $NEXT_BRIGHTNESS >> /sys/class/backlight/intel_backlight/brightness
	fi
fi

exit
