#!/bin/sh

getDate()
{
	echo "$(date "+%a %m-%d-%y %T")"
}

getAudio()
{
	STATUS=$(amixer sget Master | tail -n1 | sed -r "s/.*\[(.*)\]/\1/")
	VOL=$(amixer get Master | tail -n1 | sed -r "s/.*\[(.*)%\].*/\1/")

	if [ "$STATUS" = "off" ]; then
    	echo "Mute"
    else
		echo "Vol: $VOL%"
    fi
}

getKB()
{
	echo "$(setxkbmap -query | awk '/layout/{print $2}')"
}

getVPN()
{
	VPN=$(nmcli -a | grep 'VPN connection' | sed -e 's/\( VPN connection\)*$//g')
	if [ "$VPN" != "" ]; then
		echo " VPN: $VPN |"
	fi
}

getNetwork()
{
	CONNAME=$(nmcli -t | grep 'Wired Connection' | awk '{print $1}')
	if [ "$CONNAME" = "" ]; then
		CONNAME=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)
		if [ "$CONNAME" = "" ]; then
			echo "Offline"
		else
			IP=$(nmcli -a | grep 'inet4' | awk 'NR==1{print $2}' | cut -d '/' -f 1)
			echo "Wifi: $CONNAME $IP"
		fi
	else
		IP=$(nmcli -a | grep 'inet4' | awk 'NR==1{print $2}' | cut -d '/' -f 1)
		echo "$CONNAME $IP"
	fi
}

getBattery()
{
	BATCHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
	echo "Bat: $BATCHARGE%"
}

getRAM()
{
	USEDRAM=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==2{print $3}')
	TOTALRAM=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==2{print $2}')
	RAMUSAGE="$USEDRAM/$TOTALRAM"
	USEDSWAP=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==3{print $3}')
	TOTALSWAP=$(free -h | sed '0,/ /s/ /X/' | awk 'NR==3{print $2}')
	SWAPUSAGE="$USEDSWAP/$TOTALSWAP"
	
	if [ "$USEDSWAP" = "0B" ]; then
		echo "RAM: $RAMUSAGE"
	else
		echo "RAM: $RAMUSAGE | SWAP: $SWAPUSAGE"
	fi
}

getBrightness()
{
	CURRENTBRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/brightness)
	MAXBRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
	BRIGHTPERCENT=$(($CURRENTBRIGHTNESS*100/$MAXBRIGHTNESS))
	echo "Brightness: $BRIGHTPERCENT%"
}

parallelize()
{
	while true
	do
		sleep 2
	done
}
#parallelize &

while true
do
	xsetroot -name " $(getKB) | $(getAudio) | $(getRAM) | $(getBattery) | $(getBrightness) |$(getVPN) $(getNetwork) | $(getDate)"
	sleep 0.5
done
